### ISSUE TITLE
exec: "/entrypoint.sh": permission denied: unknown

### ISSUE THREAD

**Issue by Myfanqie** [HelloGrasscutter/HelloGrasscutter#1]
I don't know how to solve this problem. mayby need permission , but I can't find this file about  **entrypoint.sh**

![image](https://user-images.githubusercontent.com/50412437/166296234-875623f1-4cd0-4960-9f52-3918cad73cbe.png)

**Comment by Becods** [comment]
This is an issue caused by incorrectly configured permissions.
I will fix it in a later update.
